---
# handlers file for brain
- name: reload brain daemon
  become: true
  systemd:
    name: brain
    state: reloaded

- name: reload brain daemon
  listen: "restart brain and reload daemon"
  become: true
  systemd:
    name: brain
    state: reloaded

- name: restart brain
  listen: "restart brain and reload daemon"
  when: binaryAvailable
  systemd:
    state: restarted
    name: brain
