---
- block:
    - name: Check if oh-my-zsh already installed
      become: true
      stat:
        path: /home/"{{ item['name'] }}"/.oh-my-zsh
      register: oh_my_zsh_directory_details

    - name: Download zsh installer
      become: true
      command: wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
      when: oh_my_zsh_directory_details.stat.exists != true

    - name: Download zsh installer
      get_url:
        url: https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
        dest: ~/install.sh
        mode: 0755

    - name: Execute the zsh-installer.sh
      become: true
      shell: ~/install.sh
      when: oh_my_zsh_directory_details.stat.exists != true

    - name: Remove the zsh-installer.sh
      become: true
      file: path=~/install.sh state=absent
      when: oh_my_zsh_directory_details.stat.exists != true

  when: "item['name'] != '_override_'"

- name: Set oh-my-zsh-prompt
  become: true
  lineinfile:
    path: ~/.zshrc
    regexp: "^PROMPT"
    line: 'PROMPT="%n@%m%# "'
    state: present
