---
# tasks file for brain
- name: gather facts from db servers
  setup:
  delegate_to: "{{item}}"
  delegate_facts: True
  loop: "{{groups['db']}}"

- name: gather facts from messaging servers
  setup:
  delegate_to: "{{item}}"
  delegate_facts: True
  loop: "{{groups['messaging']}}"

- name: create brain user group
  group:
    name: brain
    state: present

- name: create brain user
  user:
    name: brain
    groups: brain

- name: configure brain service daemon
  template:
    src: brain.service.j2
    dest: /etc/systemd/system/brain.service
    owner: root
    group: brain
  notify: reload brain daemon
  # notify: restart brain and reload daemon
- meta: flush_handlers

- name: create resouces directory
  file:
    path: /home/brain/resources/email/template
    state: directory
    group: brain
    owner: brain

- name: extract email templates
  unarchive:
    src: emailTemplates.tar
    dest: /home/brain/resources/email/template
    extra_opts:
      - --strip=1
    group: brain
    owner: brain
