---
- name: Add yum repos
  become: true
  yum_repository:
    name: "{{ item['name'] }}"
    description: "{{ item['description'] }}"
    # file: defaults to name.repo
    baseurl: "{{ item['baseurl'] }}"
    gpgcheck: "{{ item['gpgcheck'] }}"
    gpgkey: "{{ item['gpgkey'] }}"
    # enabled: default is yes
  with_items:
    - "{{ yumRepos }}"
    - "{{ additionalYumRepos }}"

- name: Add Yum Packages
  become: true
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - ["{{ yumPackages }}", "{{ additionalYumPackages }}"]

- name: Install python packages
  become: true
  pip:
    name: "{{ pythonPackages }}"
  when: "pythonPackages | length > 0"
