---
- name: Add repos
  become: true
  yum_repository:
    name: "{{ item['name'] }}"
    description: "{{ item['description'] }}"
    # file: defaults to name.repo
    baseurl: "{{ item['baseurl'] }}"
    gpgcheck: "{{ item['gpgcheck'] }}"
    gpgkey: "{{ item['gpgkey'] }}"
    # enabled: default is yes
  with_items:
    - "{{ yumRepos }}"

- name: Add additional repos
  become: true
  yum_repository:
    name: "{{ item['name'] }}"
    description: "{{ item['description'] }}"
    # file: defaults to name.repo
    baseurl: "{{ item['baseurl'] }}"
    gpgcheck: "{{ item['gpgcheck'] }}"
    gpgkey: "{{ item['gpgkey'] }}"
    # enabled: default is yes
  with_items:
    - "{{ additionalYumRepos }}"

- name: Add Yum Packages
  become: true
  yum:
    name: "{{ item['name'] }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ yumPackages }}"

- name: Add Additional Yum Packages
  become: true
  yum:
    name: "{{ item['name'] }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ additionalYumPackages }}"
