---
# handlers file for caddy
- name: reload caddy service daemon
  become: true
  systemd:
    daemon_reload: yes
    name: caddy

- name: restart caddy
  become: true
  systemd:
    state: restarted
    name: caddy
