---
- name: Check if swap is already enabled
  become: true
  command: swapon -s
  register: swap_status

- debug:
    var: swap_status
    verbosity: 0

- block:
    - name: Create swap File
      become: true
      command: dd if="{{ if }}" of="{{ of }}" count="{{ count }}" bs="{{ bs }}"
      notify: reboot

    - name: Make swap only root readable
      become: true
      command: chmod 600 "{{ of }}"
      notify: reboot

    - name: Format file as swap
      become: true
      command: mkswap "{{ of }}"
      notify: reboot

    - name: Tell system to use it as swap
      become: true
      command: swapon "{{ of }}"
      notify: reboot

    - name: Make system use swap file on every startup
      become: true
      lineinfile:
        path: /etc/fstab
        regexp: "swapfile"
        line: '"{{ of }}" none swap sw 0 0'
        state: present
      notify: reboot

  when: swap_status.stdout == ""

- name: set swapiness
  become: true
  sysctl:
    name: vm.swappiness
    value: "{{ swappiness }}}"
    state: present
    reload: yes

- name: set vfs cache pressure
  become: true
  sysctl:
    name: vm.vfs_cache_pressure
    value: "{{ vfs_cache_pressure }}"
    state: present
    reload: yes
