---
ansible_user: surgeon
ansible_user_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFeV5DbuRfHKqK/au9Yqe+iAImzAm3+8vB6d9DVB8JwqOXlGellWooPxg2OggxvaX43DDrC7b+RfJebHwCaYBogRXgvi8jWQZmBD6nBYMYj3cbQsOoohthBkhPmSizeUQV4FkzB36mqfTg4KZ0HdUisv0zp0i9aBGSvWFn0wDTrPKy+9LpSKUbktFByxGJF2ryG6gtzgriM6dQZtAXhxcdRy8mQKkSmJRZItFL5G/UbUVbLWFeOzz8F789fZGSWfb6c6sqxQSA+MWNx6NHee6rOWTi2pOK9zWtWYbRdo/dI+S8CTE3DQBZQuTB5i1TfCztQ78N+z1eQ1cA02zP8dnP bernardbussy@FVFVXUF5J1WK-MacAir.local

timeZone: Africa/Johannesburg

# packages for all servers
yum_packages: [vim, htop]

# hosts
known_hosts:
  - name: brain01.iotmyworld.com
    key: brain01.iotmyworld.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCp2oc6MeFsPG+HIJEnmCWSwEmVkOmlizSaDj3K+lJUMJ4tvL6S4vQzzICH2Rn/+WJGcuaHFVbfsB6INwQHvU19nOYXxsd4hP7H3bGEi2RkNobYurQ6GStavX2xEpxCzPY2eSvTaDXTZLEKWQ2d+umKCR6Ox4fz97vBEeENa5WO1BFj3RmHclct5Ax4dR9+35uMBG9sQZEpK2+dv7C6HC0lLKBDrVi2Oh6HceAyJ47eMPLdmTPjPiRqPf6I0qrLCZWv/gVJuDGeiWPuYjGsuVjhUWDovwprqc90Qb0wgu37n+gn8Fko02e8gOpzvE527p5PSHvYs3UhdToeblsvr9Mj
  - name: db01.iotmyworld.com
    key: db01.iotmyworld.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDUxTwCiMp5cIhSsMzM4a+xwWoDuGtKJKKKCfaL4DMGEjfL4vMfv8WPAOg9fRuq/80AQ23ZGIuZOu+fpxg9HHDyrEXP4Z/opD5jvI1U3y/CNWiPsejhjNaVtNcICP/iG1vC3eo0JBMtPaYaBHK6smhuruOirHa/LxiI5KnZBPu1BJNeglXPJX4G+pIzlnidLQmHIDIE8pUW7KDZxrf9EdoWDnEl+LgKhCFHDdp0BVAW9r04zzPqtg4g3sZFJ4Ys0xxkFPvgf7OqF/4Qi8528fn6ceXblUhzL7xuu3Imknm7mG3fHheAudzHO1TKGGoM4Skm/qnDReKMoila4RAQO5rp

# users to add on each server
users:
  - name: bernard
    groups: [sudo, bernard]
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBlA9WrDicm09MJLi3l69NNmxI/vRmuoR6j0YlticPqQcoxEOiaC4HMB5l74Ho63A9oUwloHqqORg/qgEqS2FR54xcrIP/1uCwtQcu0TzYKiIrISNsW/6sqVbzzN0b+sF+/vcyNNKwhSm6KBF3G4lSBUx7AaYHC6Ps38OLdDV1cWCw6w2/jM4cklj8g0c8hOgMBX1nT2I3QtHkaXj8fStRUQUYKd0xMIc1ojECW2oM85Bll57LLKulfnKh9JOts+HdAdfMuUDdOHAmg+7MyXsFXXlkzXtl9b/oxHvID9j7IS0/VPyEiowUMkuTYrWdu7FazSEBkTTE4lT4BDqwI8j3 bernardbussy@FVFVXUF5J1WK-MacAir.local

# nerve vars
nerve_socket_server_port:

# brain vars
brain_api1_server_port: 9010
brain_api2_server_port: 9011

# kafka vars
kafka_port: 9092

# mongo vars
mongo_authorization: enabled
# mongo_authorization: disabled
mongo_port: 27017
mongo_user:
  name: brain
  password: "theInsideOfTheBrainContainsNeurons"
  roles: ["userAdminAnyDatabase", "readWriteAnyDatabase"]
mongo_root_user:
  name: amygdala
  password: "controllerOfAllMemories"
