---
ansible_user: surgeon
ansible_user_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFeV5DbuRfHKqK/au9Yqe+iAImzAm3+8vB6d9DVB8JwqOXlGellWooPxg2OggxvaX43DDrC7b+RfJebHwCaYBogRXgvi8jWQZmBD6nBYMYj3cbQsOoohthBkhPmSizeUQV4FkzB36mqfTg4KZ0HdUisv0zp0i9aBGSvWFn0wDTrPKy+9LpSKUbktFByxGJF2ryG6gtzgriM6dQZtAXhxcdRy8mQKkSmJRZItFL5G/UbUVbLWFeOzz8F789fZGSWfb6c6sqxQSA+MWNx6NHee6rOWTi2pOK9zWtWYbRdo/dI+S8CTE3DQBZQuTB5i1TfCztQ78N+z1eQ1cA02zP8dnP bernardbussy@FVFVXUF5J1WK-MacAir.local
brainMongoUserPassword: theInsideOfTheBrainContainsNeurons

# packages
yumPackages:
  - vim

# Users
systemUsers:
humanUsers:
  - name: bernard
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEZ+FBugBJnIB3mj6NMb0kULOik+SxIRReH7JVmAfR4IVU7WxmK80X9hFUYit4wmwSUlcx0h2Lpck/vL48SNo1tBTaW4oKN1KS/KxS3JwyA7Goh6j9Gzn+jnELu219hZoU49nXZ440Q56iDqwjjeCbXZN90wgiVAjgIfp57qi6230aqELLbN8IYlCy9aIbH1SHVaLtA622rQjRI9R5y3V9FhZy+MP6mka4DSKND8trcr8kQPvdLNzoFQyroGBEYsy8LCCBrhlw8mr5VsDGtj64+77yjUL+H4jB92ex4Bn1yxzGKQmsy+oomKM1D0dK5jXbXrBMAfYDeIV9GKzNzuf7 bernardbussy@BernardsApple.local
