---
ansible_user: surgeon
ansible_user_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFeV5DbuRfHKqK/au9Yqe+iAImzAm3+8vB6d9DVB8JwqOXlGellWooPxg2OggxvaX43DDrC7b+RfJebHwCaYBogRXgvi8jWQZmBD6nBYMYj3cbQsOoohthBkhPmSizeUQV4FkzB36mqfTg4KZ0HdUisv0zp0i9aBGSvWFn0wDTrPKy+9LpSKUbktFByxGJF2ryG6gtzgriM6dQZtAXhxcdRy8mQKkSmJRZItFL5G/UbUVbLWFeOzz8F789fZGSWfb6c6sqxQSA+MWNx6NHee6rOWTi2pOK9zWtWYbRdo/dI+S8CTE3DQBZQuTB5i1TfCztQ78N+z1eQ1cA02zP8dnP bernardbussy@FVFVXUF5J1WK-MacAir.local

timeZone: Africa/Johannesburg

# packages for all servers
yum_packages: [vim, htop]

# hosts
known_hosts:
  - name: brain01.spotnav.net
    key: brain01.spotnav.net ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDsZ1g7dxPCU0BowcjeQv4WJ08U+sQNHEziDPW7TcvE85WHYljvqpUOXdDSdpfOwO69mrG+sv+VhCoaUsYwKC1OB6ioKlHiSuwgEkjleLTQqR76YVMsMBlObQBIGSzaMpGePeK+rcMFgL90zMs8WHywmjSCUaGTp8JHAKRGuNuuIWhDT+AX1XIqlgiMmFYZI0vuANOceGELTEYhN0cbvio50eqTiR7oK3i1iHZbva9UYEYBpDsPAxY/tIibxOkISY5ItSVsQFBMbyxdHnaUPeo+2iG+cyn/nmW1p9H5f33oumcwZZq7qAtuAQ9EMbsTKzezfoZs//ZSwXmxqA0F+VeN
  - name: nerve01.spotnav.net
    key: nerve01.spotnav.net ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDYECeix2VtrZiSLj7gjGNksYdPdG1WmddUj+UTN2xs8P8qTRrUL08QhADJYCvyiWqUFn8oQrEs9IjgBg7DJs3OWZh30U7rYYZfpnFaNfNrB9tKGJGTDYh0QqdPt+zwILMcOKMKAZNA5r/eu5KSBw8L69ESbfYXtPYCdyLQsEJuTuXodQD8D4yP39w9A/YsZtPK25AH1QRGiP1cf9ZFl0rqR1Htt2LHMqGdXz4slJwceRSLYpr/2MyTKP9C9LPAlaIOGhSAG89Cf45F5DTllNuoP179fSM4m//b8/wSZh7DVikMffXcIlFYgWUcIOTJh1wLsyrafJeJ3XJkNf//QptV
  - name: messaging01.spotnav.net
    key: messaging01.spotnav.net ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1klifWoW+bweDGjPQgC+UiJfbmUqU4zXkpPJIhkAU+uS5Om3/0XQOpQ1NwdOs0xZSfY17tKWjnj68aEvd1TNxSIWgFZVsLNoMz/HqB39g9fRbfDcxAFLbqSRSoIB9F0ZX6YpvRpmCXiWTlYjci5WIvDJulkrg4nMg0LHpGL/qg4VP7l+vFj4LpATvHmimpkrKeP4YR5Rs4VTcqKTCmR1nqkFh/ukPvVk9ve1Kx3rkwxb9tBwaAui1rkXKsUjL2NE9bt7pP8hrzwQnolbFiOq10OAIDK0hWOXkg5XJtjP4aqxMV/iKYeM51HQKWpolevBCA0xjHcx7oYKQqhgaSyu9
  - name: db01.spotnav.net
    key: db01.spotnav.net ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCrW5clNgV+u8alG2rCwdHBQqiMn8NF5sUwopSTIqy+odsJNgGK2/q08K5Twgj9X3BI4wiPblURO+g8z/tSZZtmARTmvFAi9KgejOWPPn1oPQgjqdxKXc+mCUH8O65aI0KkTewJ6CxXmE0MPPHN5yz+4soBufbgwInxxcfReVHG8ngJj4W88RyVqP8Vm4kFDoKGWtJp69bBhywyNhezA8y6uUw7/oHKvBNG+HgMny+Pj497c0HdzxRZzUk17FJ6WtlXMN5LPAbq/nuTuG/q+DWlgcLCwno9dYUmFPwRukU4vPHdnY4T+ZCE+/xqS7Q5ZBb2pUYnkys1vhjOhOzyXfPv

# users to add on each server
users:
  - name: bernard
    groups: [sudo, bernard]
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBlA9WrDicm09MJLi3l69NNmxI/vRmuoR6j0YlticPqQcoxEOiaC4HMB5l74Ho63A9oUwloHqqORg/qgEqS2FR54xcrIP/1uCwtQcu0TzYKiIrISNsW/6sqVbzzN0b+sF+/vcyNNKwhSm6KBF3G4lSBUx7AaYHC6Ps38OLdDV1cWCw6w2/jM4cklj8g0c8hOgMBX1nT2I3QtHkaXj8fStRUQUYKd0xMIc1ojECW2oM85Bll57LLKulfnKh9JOts+HdAdfMuUDdOHAmg+7MyXsFXXlkzXtl9b/oxHvID9j7IS0/VPyEiowUMkuTYrWdu7FazSEBkTTE4lT4BDqwI8j3 bernardbussy@FVFVXUF5J1WK-MacAir.local

brain_mongo_user:
  - name: brain
    password: "theInsideOfTheBrainContainsNeurons"
    roles: ["userAdminAnyDatabase", "readWriteAnyDatabase"]
