---
ansible_user: surgeon
ansible_user_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFeV5DbuRfHKqK/au9Yqe+iAImzAm3+8vB6d9DVB8JwqOXlGellWooPxg2OggxvaX43DDrC7b+RfJebHwCaYBogRXgvi8jWQZmBD6nBYMYj3cbQsOoohthBkhPmSizeUQV4FkzB36mqfTg4KZ0HdUisv0zp0i9aBGSvWFn0wDTrPKy+9LpSKUbktFByxGJF2ryG6gtzgriM6dQZtAXhxcdRy8mQKkSmJRZItFL5G/UbUVbLWFeOzz8F789fZGSWfb6c6sqxQSA+MWNx6NHee6rOWTi2pOK9zWtWYbRdo/dI+S8CTE3DQBZQuTB5i1TfCztQ78N+z1eQ1cA02zP8dnP bernardbussy@FVFVXUF5J1WK-MacAir.local
brainMongoUserPassword: theInsideOfTheBrainContainsNeurons

timeZone: Africa/Johannesburg

# packages for all servers
yum_packages: [vim, htop]

# hosts
known_hosts:
  - name: brain01.spotnav.net
    key: brain01.spotnav.net ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDiT9qLz2aHh40vXDIr2IHdeAtM/MjLc4ZDA95FLQcIgFdee9XeltbIknKPJ0FtCo5dvzYYGEsT2quit9hN+olILawGU7+JcyJFqtuU4QX3vT3Yr1huZSSezQBR5y/urQFagMCwQVGCUpFpuRNZCgPEqU+x3bJ0FHqfjQ5Urs+T1e4syM5O9fqQujlfAcu4DMr5BuHNLHEfWsduzkK9nj5seivPrmj/g5d09EDsoy4r7x661yfY9aLpwb8+pUkPC0ZktK5f+OnQVxjhmN3vPOL0W0xju4cpl1tn+lOOPSVvY0OoOlg49z7W6cYkRjiCNwG+0PadwMe4cyGd++SHAsmX
  - name: nerve01.spotnav.net
    key: nerve01.spotnav.net ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCXFZ8g9qy1qmjeG0t4ipvpgSMNosGX+FK/RpxG4ndu49eQvcLDqpyVRdW8enDW8oN220HjOrgu4I705nbwUm3/5ykVOesffcw4iNzviG9+hBsDyjD0012VbS9YLiHniKWlJs8FBlZiENzfvPi/WFc8AlY6Lh8MIKmM0qoJ7zbDs23/hocyNDg7BVQ/HRbe5tIcnWtV+RztCf9b/Icqwz9qwMU1PEuyiskz6Lb9jMn+xCcmzPTa7d4dETSKs7ecob5niDBIrDvDNNAfGzuHw3iiZ58jO+iYO0mUVesuT1vDdUVXleABKztyMISuRLFFxnQawCOqOa8+3xoc/TmI1cXZ
  - name: messaging01.spotnav.net
    key: messaging01.spotnav.net ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCZBGJfK4xRjJT01bw8P/x6IMXPsuQ7lYWvl0Dh5hzT9QsU/1OX36QjtkHPdyVjBgkeEwK3AI66+W7B7dpJksQWwr9lt8eyd0tLambAWGZKN2KPmys4b18Lc7CSt8xtqhA0DxOFZKPBuF39hGFLB8gw8rLJ7GmaZVVK8sAVtgGHONR3i36Xo+YShuWWr9I3tIFuFEmYOzKEgOjybH1aZ0FituGNPaJjVwDPD76b3+evNAEOWwdxsF3rerjpD2uC6S9H2Sb9GZSb8NycZIcBkK1hcTiYlT7UNMxpuc1mDCjD/PuO09nIA6JO2VG5zqyyUwGqDwFDU1g389jpEYquoiXd
  - name: db01.spotnav.net
    key: db01.spotnav.net ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwjL9luDge4+cZxjVwXwQ2V9wsZ8MlIgFpFqSzMawSjDPJsD8gYBbZtPRHw30Ma6C9UIkdonmzAZTWNJRZKJAwsoBgOAyC9X2rz5ps7Dk5zLn7gU9rKoo22Rz9E3zgk0seFLyASgSgJZ/QP3408iwERxQwDjCvOqYfx3suyMeDoBueDcAmleOprZHGK/yv5TVXLBLiztcMBT3Dz02PYTmTA2uD8gj5/mRYj3qApG83VyYpsmMvFImdQOjbkqgE+Jyap25m4fp8uNCzTqAvYXBl6Dpv2J8myPmTgN3fBUONr6LOhpwy/8oQyYHtvFGNUTkDyzP03PVsHDg7/dUAJBlp

# users to add on each server
users:
  - name: bernard
    groups: [sudo, bernard]
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEZ+FBugBJnIB3mj6NMb0kULOik+SxIRReH7JVmAfR4IVU7WxmK80X9hFUYit4wmwSUlcx0h2Lpck/vL48SNo1tBTaW4oKN1KS/KxS3JwyA7Goh6j9Gzn+jnELu219hZoU49nXZ440Q56iDqwjjeCbXZN90wgiVAjgIfp57qi6230aqELLbN8IYlCy9aIbH1SHVaLtA622rQjRI9R5y3V9FhZy+MP6mka4DSKND8trcr8kQPvdLNzoFQyroGBEYsy8LCCBrhlw8mr5VsDGtj64+77yjUL+H4jB92ex4Bn1yxzGKQmsy+oomKM1D0dK5jXbXrBMAfYDeIV9GKzNzuf7 bernardbussy@BernardsApple.local
