---
# tasks file for group
- name: Create groups
  become: true
  group:
    name: "{{ item['name'] }}"
    state: present
  with_items:
    - "{{ systemUsers }}"
    - "{{ additionalSystemUsers }}"
    - "{{ humanUsers }}"
    - "{{ additionalHumanUsers }}"

- name: Remove additional groups
  become: true
  group:
    name: "{{ item['name'] }}"
    state: absent
  with_items:
    - "{{ groupsToRemove }}"
    - "{{ additionalGroupsToRemove }}"
