---
# tasks file for group
- name: Create groups for users
  become: true
  group:
    name: "{{ item['name'] }}"
    state: present
  with_items:
    - "{{ users }}"

- name: Remove additional groups
  become: true
  group:
    name: "{{ item['name'] }}"
    state: absent
  with_items:
    - "{{ groups_to_remove }}"
