---
# tasks file for mongo
- name: add mongo db repo
  yum_repository:
    name: mongodb-org-4.0
    # name: becomes 'repo id' in repolist
    description: MongoDB Repository
    # description: becomes 'repo name' in repolist
    # file: defaults to name.repo
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.0/x86_64
    gpgcheck: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-4.0.asc
    # enabled: default is yes
    mode: 0644
    state: present

- name: install mongo
  become: true
  yum:
    name: mongodb-org
    state: present
    update_cache: yes

- name: ensure mongo started and enabled
  become: true
  service: name=mongod state=started enabled=yes

- name: set up brain user on mongo db
  become: true
  mongodb_user:
    database: admin
    name: brain
    password: "{{ brainMongoUserPassword }}"
    update_password: always
    roles:
      - "userAdminAnyDatabase"
      - "readWriteAnyDatabase"
    state: present
