---
- name: Add EPEL Repo
  yum_repository:
    name: epel-release-latest-7
    description: MongoDB Repository
    # file: defaults to name.repo
    baseurl: https://dl.fedoraproject.org/pub/epel/7Server/aarch64/
    gpgcheck: yes
    gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
    # enabled: default is yes

- name: Add MongoDB Repo
  yum_repository:
    name: mongodb-org
    description: MongoDB Repository
    # file: defaults to name.repo
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.0/x86_64/
    gpgcheck: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-4.0.asc
    # enabled: default is yes

- name: install required packages
  yum:
    name:
      - vim
      - mongodb-org
      - python-pip
    state: present
    update_cache: yes

- name: install required python packages
  pip:
    name: pymongo

- name: enable authentication on mongodb
  blockinfile:
    path: /etc/mongod.conf
    insertafter: "^#security:"
    block: |
      security:
        authorization: "enabled"
  notify: restart mongodb

- name: ensure mongo started and enabled
  service: name=mongod state=started enabled=yes

- name: set up brain user on mongo db
when: false
mongodb_user:
  database: admin
  name: brain
  password: "{{ brainMongoUserPassword }}"
  update_password: always
  roles:
    - "userAdminAnyDatabase"
    - "readWriteAnyDatabase"
  state: present
