---
- name: Create sudo group
  group:
    name: sudo
    state: present

- name: Remove password requirement for sudo users
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%sudo.*ALL=NOPASSWD:.*ALL"
    insertafter: "^%sudo.*ALL=(ALL:ALL).*ALL"
    line: "%sudo ALL=NOPASSWD: ALL"

- name: Create "{{ ansible_user }}" user group
  group:
    name: "{{ ansible_user }}"
    state: present

- name: Create "{{ ansible_user }}" user
  user:
    name: "{{ ansible_user }}"
    # password: # using pgp key login
    groups:
      - wheel
      - sudo
      - "{{ ansible_user }}"
    append: yes

- name: Set authorized key for "{{ ansible_user }}"
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ ansible_user_public_key }}"
    state: present
