---
- name: Create sudo group
  become: true
  group:
    name: sudo
    state: present

- name: Remove password requirement for sudo users
  become: true
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%sudo.*ALL=NOPASSWD:.*ALL"
    insertafter: "^%sudo.*ALL=(ALL:ALL).*ALL"
    line: "%sudo ALL=NOPASSWD: ALL"

- name: Create "{{ ansible_user }}" user group
  become: true
  group:
    name: "{{ ansible_user }}"
    state: present

- name: Create "{{ ansible_user }}" user
  become: true
  user:
    name: "{{ ansible_user }}"
    # password: # using pgp key login
    groups:
      - wheel
      - "{{ ansible_user }}"
    append: yes

- name: Set authorized key for "{{ ansible_user }}"
  become: true
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ ansible_user_public_key }}"
    state: present

- name: Disallow password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: Restart ssh

- name: Disallow root SSH access
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: Restart ssh
