---
# tasks file for caddy
- name: Allow http through Firewall
  become: true
  firewalld:
    service: http
    immediate: yes
    permanent: yes
    state: enabled

- name: Allow https through Firewall
  become: true
  firewalld:
    service: https
    immediate: yes
    permanent: yes
    state: enabled

- name: Create group for caddy
  become: true
  group:
    name: caddy
    state: present

- name: Create user for caddy
  become: true
  user:
    name: caddy
    groups: [caddy]
    system: yes

- name: copy caddy binary to server
  become: true
  copy:
    src: caddy
    dest: /usr/local/bin/caddy

- name: create directory for CaddyFile
  become: true
  file:
    path: /etc/caddy
    state: directory
    owner: root
    group: caddy

- name: configure Caddyfile
  become: true
  template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: root
    group: caddy
  notify: restart caddy

- name: configure caddy service daemon
  become: true
  template:
    src: caddy.service.j2
    dest: /etc/systemd/system/caddy.service
    owner: root
    group: caddy
  notify: reload and restart caddy

- name: create directory for SSL keys for https
  become: true
  file:
    path: /etc/ssl/caddy
    state: directory
    owner: caddy
    group: root
    mode: 0770

- name: make website directory
  become: true
  file:
    path: /var/www
    state: directory
    owner: caddy
    group: caddy

- name: start and enable caddy
  become: true
  systemd:
    state: started
    enabled: yes
    name: caddy
