---
- hosts: brain, nerve, messaging, db
  roles:
    - installEpelRepo

- hosts: brain, nerve, messaging, db
  gather_facts: false
  tasks:
    - name: Add Yum Packages
      become: true
      yum:
        name: "{{ yum_packages }}"
        state: present
        update_cache: yes
